const http = require('http') ;

const server = http.createServer((request, response)=>{
    response.end("......... Hello From Server Side (This is the response generated by the Server) .......");
}) ;

const port = 8765 ;
const localHost = '127.0.0.1' ;

server.listen(port, localHost, ()=>{
    console.log(`Your Server is listening at localhost:${port}`) ;
}) ;